### ISSUE TITLE
customizable prefix

### ISSUE THREAD

**Issue by fenio** [danielfoehrKn/kubeswitch#156]
I use multiple non-local configstores like this:

```
kind: SwitchConfig
version: v1alpha1
kubeconfigStores:
- kind: akamai
  id: foo
  config:
    linode_token: "randomstuff"
- kind: akamai
  id: bar
  config:
    linode_token: "randomstuff"
```

Example shows just two of them but in practice there's much more. Thing is that after running switch it's not possible to differentiate which cluster comes from which configstore. AFAICS it's not possible to fix it on provider side.

Would be great to have option to modify / customize prefix.

Something like useIDasPrefix. Right now all my clusters are prefixed with "akamai" which isn't really helpful if ALL of them are in Akamai ;)
