### ISSUE TITLE
Feature request - capi store should support more than one kubeconfig

### ISSUE THREAD

**Issue by networkhell** [danielfoehrKn/kubeswitch#174]
Problem: The cluster-api (capi) store currently supports searching the current context as well as **one** statically configured kube-config to search for capi management clusters. 

As capi user you likely run more than one capi manager e.g. dev/production managers. It is cumbersome to either switch the current context to discover workload clusters or even change the config path to point to another manager cluster.

Most stores e.g. Filesystem support regex matching of kubeconfig files e.g. 
```yaml
kind: SwitchConfig
version: v1alpha1
kubeconfigName: "config"
kubeconfigStores:
- kind: filesystem
  kubeconfigName: "*.kubeconfig"
  paths:
  - ~/.kube/kubeconfigs
- kind: capi
  config:
    # Optionally specify a kubeconfigPath for a management cluster,
    # if not specified your current kube context will be searched for any CAPI clusters
    kubeconfigPath: "/Users/foo/.kube/kubeconfigs/mgmt-dev.kubeconfig"
```

The config node **kubeconfigPath** does neither support directories nor multiple files via pattern matching. Even ~/.kube/config fails because it seems that ~ is not resolved to $HOME. 

It would be super helpful if you could add support for multiple capi manager kubeconfigs like the filesystems store does right now with a list of *paths* and *kubeconfigName* with support for pattern matching.

**Comment by guilhem** [comment]
Hello @networkhell 
`kubeconfigPath` in CAPI is not the same as one in `filesystem`.
In filesystem, it lets you discover multiple clusters and gives you choices after.

For CAPI, path is used by internal capi implementation to connect to managment cluster. In fact, it's even only the default context that will be used.
We don't have a way to give a first selection of mgmt cluster to discover clusters after.

But to get multiple capi, you can duplicate configuration block with a different name:
```yaml
- kind: capi
  name: dev
  config:
    # Optionally specify a kubeconfigPath for a management cluster,
    # if not specified your current kube context will be searched for any CAPI clusters
    kubeconfigPath: "/Users/foo/.kube/kubeconfigs/mgmt-dev.kubeconfig"
- kind: capi
  name: prof
  config:
    # Optionally specify a kubeconfigPath for a management cluster,
    # if not specified your current kube context will be searched for any CAPI clusters
    kubeconfigPath: "/Users/foo/.kube/kubeconfigs/mgmt-prod.kubeconfig"
```
