### ISSUE TITLE
Gardener store fails to target garden clusters (virtual garden)

### ISSUE THREAD

**Issue by networkhell** [danielfoehrKn/kubeswitch#175]
Current setup: 
```
OS: macOS 15.4
shell: fish, version 4.0b1
switcher: v0.9.3
```

I confgured my garden store like this
```yaml
- kind: gardener
  config:
    gardenerAPIKubeconfigPath: "~/.kube/kubeconfigs/garden-dev.kubeconfig"
    landscapeName: "dev"
- kind: gardener
  config:
    gardenerAPIKubeconfigPath: "~/.kube/kubeconfigs/garden-staging.kubeconfig"
    landscapeName: "staging"
```

In general it works as expected and I am able to target seeds and shoots. But the discovery of the virtual garden contexts fail with the error messages
```
25R250000] failed to write alias dev-garden for context name dev-garden  store=gardener
  38R380000] failed to write alias staging-garden for context name staging-garden  store=gardener
```
I have no idea how I can further debug this issue. Are there any naming constraints?
