### ISSUE TITLE
GKE store: no projects found in Google Cloud

### ISSUE THREAD

**Issue by Zebradil** [danielfoehrKn/kubeswitch#63]
### Prerequisites:

```yaml
# ~/.kube/switch-config.yaml
kind: SwitchConfig
version: "v1alpha1"
kubeconfigStores:
  - kind: gke
    id: gke
    config:
      authentication:
        authenticationType: gcloud
      # optionally limit to certain projects in account
      # projectIDs: []
```

### Steps to reproduce:

0. Run `switch` (Google Cloud Authorization opens in a web browser)
1. Allow access
2. Wait a little bit, then exit from `switch`

### Result:

```console
$ switch
WARN[0021] Supressed warnings during the search: 1 error occurred:
        * store "gke.gke" returned an error during the search: failed to initialize store: no projects found in Google Cloud. Unable to discover GKE clusters

Error: abort
```

### Expected

A list of GKE clusters. There are definitely some projects:

```console
$ gcloud projects list | wc -l
5
```

And some GKE clusters:

```console
$ gcloud container clusters list | wc -l
2
```

### Additional information

Kubeswitch version info:

```
Switch:
		version     : v0.7.2
		build date  : 2022-09-20
		go version  : go1.19
		go compiler : gc
		platform    : linux/amd64
```

Gcloud version info:

```
Google Cloud SDK 404.0.0
alpha 2022.09.23
beta 2022.09.23
bq 2.0.78
bundled-python3-unix 3.9.12
core 2022.09.23
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.4.0
gsutil 5.14
```
