### ISSUE TITLE
FR: Support post-picking hooks

### ISSUE THREAD

**Issue by hinricht** [danielfoehrKn/kubeswitch#77]
It seems from reading the [hook docs](https://github.com/danielfoehrKn/kubeswitch/blob/master/hooks/README.md) that 

> Hooks are executed prior to the fuzzy search via $ switch or can be called directly via $ switch hooks --hook-name=<name>.

I'd like to call a hook immediately *after* I picked the context. I.e. setting the right gcloud config depending on the k8s context.

Is this sth that could be easily implemented ?

i.e. adding a `type` key to `execution` ?

```
 kind: SwitchConfig
hooks:
  - name: inline
    type: InlineCommand
    type: Executable
    path: "/home/hinricht/bin/gcloud-config.sh"
    execution:
      type: post
```
