### ISSUE TITLE
garden integration broken

### ISSUE THREAD

**Issue by MichaelSp** [danielfoehrKn/kubeswitch#83]
I've configured 
gardener with the following options:

```
# ~/.garden/gardenctl-v2.yaml
gardens:
  - identity: "landscape-canary"
    kubeconfig: "~/.garden/landscape-canary.yaml"
  - identity: "landscape-live"
    kubeconfig: "~/.garden/landscape-live.yaml"
```

```
# ~/.kube/switch-config.yaml
kind: SwitchConfig
version: v1alpha1
showPreview: false
refreshIndexAfter: 4h
kubeconfigStores:
- kind: gardener
  paths:
  - "garden"
  config:
    gardenerAPIKubeconfigPath: "~/.garden/landscape-canary.yaml"
    landscapeName: "landscape-canary"
- kind: gardener
  refreshIndexAfter: 6h
  config:
    gardenerAPIKubeconfigPath: "~/.garden/landscape-live.yaml"
    landscapeName: "landscape-live"
```

The WARN message:
* `store "gardener.landscape-live" returned an error during the search: failed to initialize store. This is most likely a problem with your provided kubeconfig: unable to get gardener landscape identity from config map kube-system/cluster-identity: configmaps "cluster-identity" is forbidden: User "my@email.com" cannot get resource "configmaps" in API group "" in the namespace "kube-system"`

Why does kubeswitch want to lookup the `cluster-identity`? That's already in the config.
